### ISSUE TITLE
MissingPluginException 

### ISSUE THREAD

**Issue by emmaxCreative** [fluttercommunity/flutter_wear_plugin#7]
Any idea why I get MissingPluginException for `getShape` and `isAmbient` ?

I tried starting the example from this package. Its starting on the emulator and works but it throws this exceptions everytime.

```
Dart Unhandled Exception: MissingPluginException(No implementation found for method getShape on channel wear), stack trace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 9769): <asynchronous suspension>
E/flutter ( 9769): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 9769): #2      Wear.getShape (package:wear/src/wear.dart:60:29)
E/flutter ( 9769): #3      _WatchShapeState.initState (package:wear/src/shape_widget.dart:43:19)
E/flutter ( 9769): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter ( 9769): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9769): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9769): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
E/flutter ( 9769): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #10     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 9769): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 9769): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 9769): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 9769): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 9769): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 9769): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #38     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 9769): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 9769): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 9769): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #45     SingleChildRenderOb
E/flutter ( 9769): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: MissingPluginException(No implementation found for method isAmbient on channel wear), stack trace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 9769): <asynchronous suspension>
E/flutter ( 9769): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 9769): #2      Wear.isAmbient (package:wear/src/wear.dart:71:29)
E/flutter ( 9769): #3      _AmbientModeState.initState (package:wear/src/ambient_widget.dart:50:19)
E/flutter ( 9769): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter ( 9769): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9769): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9769): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 9769): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 9769): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9769): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9769): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 9769): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 9769): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9769): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9769): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 9769): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #21     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 9769): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 9769): #24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter ( 9769): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 9769): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 9769): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
E/flutter ( 9769): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 9769): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 9769): #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 9769): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 9769): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 9769): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 9769): #43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 9769): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
```

**Comment by qianxuechao** [comment]
http://blog.z7ge.com/archives/flutter-missingpluginexception-bu-yao-huang 希望能帮到你

**Comment by JeisonSanches** [comment]
Any update?

**Comment by slightfoot** [comment]
This is not an issue with the plugin. You have forgotten if you add a package to your pubspec.yaml with a native component you have to stop your app and start it fresh so Gradle or XCode can build the native part. Otherwise you are just Hot-reloading the Dart portion of your app.
